version: '3.9'
services:
  postgres:
    image: postgres:17
    container_name: my-postgres
    restart: always
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

#  redis:
#    image: redis:7.2
#    container_name: my-redis
#    ports:
#      - "6379:6379"

#  minio:
#    image: minio/minio:latest
#    container_name: my-minio
#    ports:
#      - "9000:9000" # API
#      - "9001:9001" # Web-консоль
#    environment:
#      MINIO_ROOT_USER: admin
#      MINIO_ROOT_PASSWORD: password123
#    command: server /data --console-address ":9001"
#    volumes:
#      - minio_data:/data

volumes:
  postgres_data:
  minio_data:
