-- liquibase formatted sql file

-- changeset tkachev:1
create table person(
                       id int primary key generated by default as identity ,
                       username varchar(50) not null unique,
                       password varchar(100) not null,
                       role varchar(20) not null
);
-- rollback DROP TABLE person;

